---
apiVersion: v1
kind: Secret
metadata:
  namespace: ns-chatbot-ui
  name: secret-aoai-chatbot-ui
type: Opaque
stringData:
  OPENAI_API_KEY: "<API key>" # TODO
  AZURE_DEPLOYMENT_ID: "<deployment id>" # TODO
  OPENAI_API_HOST: "https://<AOAI NAME>.openai.azure.com/" # TODO
  OPENAI_API_TYPE: "azure"
  DEFAULT_MODEL: "gpt-35-turbo"
  OPENAI_API_VERSION: "2023-03-15-preview"
