---
apiVersion: v1
kind: Service
metadata:
  name: lb-podinfo
  namespace: ns-podinfo
spec:
  type: LoadBalancer
  selector:
    app: podinfo
  ports:
    - name: http # Just a name
      port: 9898 # the port for client to access
      protocol: TCP # TCP or UDP
      targetPort: http # the port that Pod listen on
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: ns-podinfo
spec:
  type: ClusterIP
  selector:
    app: podinfo
  ports:
    - name: http # Just a name
      port: 9898 # the port for client to access
      protocol: TCP # TCP or UDP
      targetPort: http # the port that Pod listen on
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc