---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider-aoai
  namespace: chatgpt-lite
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "81504550-8929-4447-8c5f-dd9e9eae2237"
    tenantId: "16b3c013-d300-468d-ac64-7eda0820b6d3"
    keyvaultName: "kv-aoai"
    cloudName: "AzurePublicCloud"
    objects:  |
      array:
        - |
          objectName: secret-aoai-api-base-url
          objectType: secret
          objectVersion: ""
        - |
          objectName: secret-aoai-api-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: secret-aoai-deployment
          objectType: secret
          objectVersion: ""
  secretObjects:
  - secretName: secret-aoai
    type: Opaque
    data:
      - objectName: secret-aoai-api-base-url
        key: secret-aoai-api-base-url
      - objectName: secret-aoai-api-key
        key: secret-aoai-api-key
      - objectName: secret-aoai-deployment
        key: secret-aoai-deployment